import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const mockupRoot = path.join(repositoryRoot, "docs", "pantalles");
const iconRoot = path.join(repositoryRoot, "packages", "ui", "src", "icons");
const symbolPattern = /<symbol\s+id="i-([^"]+)"[^>]*>[\s\S]*?<\/symbol>/g;

async function htmlFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        return htmlFiles(entryPath);
      }
      return entry.isFile() && entry.name.endsWith(".html") ? [entryPath] : [];
    }),
  );
  return nested.flat();
}

const symbols = new Map();
const files = (await htmlFiles(mockupRoot)).sort();

for (const file of files) {
  const source = await readFile(file, "utf8");
  for (const match of source.matchAll(symbolPattern)) {
    const name = match[1];
    const symbol = match[0];
    if (name !== undefined && symbol !== undefined && !symbols.has(name)) {
      symbols.set(name, symbol);
    }
  }
}

const names = [...symbols.keys()].sort();
const sprite = [
  '<svg xmlns="http://www.w3.org/2000/svg">',
  "  <defs>",
  ...names.map((name) => `    ${symbols.get(name)}`),
  "  </defs>",
  "</svg>",
  "",
].join("\n");
const namesModule = [
  "// Generated by scripts/extract-icons.mjs. Do not edit by hand.",
  "export const ICON_NAMES = [",
  ...names.map((name) => `  ${JSON.stringify(name)},`),
  "] as const;",
  "",
  "export type IconName = (typeof ICON_NAMES)[number];",
  "",
].join("\n");

const spritePath = path.join(iconRoot, "sprite.svg");
await Promise.all([
  writeFile(spritePath, sprite, "utf8"),
  writeFile(path.join(iconRoot, "names.ts"), namesModule, "utf8"),
]);

console.log(`Extracted ${names.length} icons to ${path.relative(repositoryRoot, spritePath)}`);
